name: Continuous Integration - Builds

on:
	pull_request:
		branches: [master]

jobs:
	build_pull_request:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@master
			- uses: actions/setup-dotnet@v1
		   	  with:
		 	    dotnet-version: '3.1.10'
			- run: nuget restore MoneroClient.sln
			- run: dotnet build MoneroClient.sln